function loadData(data){
	if ('Free Services' == data){
		document.getElementById("description").innerHTML = "<p1>Free Services</p1><br><p>You are entitled to one free service within the first year of purchase. We offer a comprehensive 5-year warranty and a service level agreement on all acoustic pianos; this includes free maintenance and tuning. We offer a buy back for the full purchase price of a guitar when you upgrade to a new guitar within the first year of purchase. This offer is contingent on the condition of the guitar.</p><br><p1>Free Music Lessons</p1><br><p>If you purchase a keyboard or digital piano you are eligible to receive one free lesson. All classes are conducted by professionals at the Sonidos.</p>";
		
	}else if ('Guarantee' == data){
		document.getElementById("description").innerHTML = "<p1>Conditions of Guarantee</p1><br><p2><b>We want our products to be nothing but a source of joy to you and all items are covered by a comprehensive guarantee and supporting warranty. These are the terms and conditions governing this agreement.</b></p2><br><li>Your purchase must have been made from us or from an authorized dealer.</li><li>The guarantee card cannot be transferred.</li><li>If you find the product to be defective in any way, during its warranty period, we will repair it. However, the returning of a product is entirely your responsibility, including any cost incurred.</li><li>The liability we assume is only for the guarantee period. This guarantee is limited to the cost of repair, and/or spare parts which have found to be defective due to faulty workmanship or material.</li><li>The guarantee does not cover loss, defects or damage caused by abuse, misuse, power fluctuations, acts of god or improper installation and workmanship.</li><li>Any attempts to test, refurbish, repair or modify equipment by persons unauthorized to do so will immediately invalidate the warranty.</li><li>If after testing, the returned product is found to be not defective, a fee for testing the product will be levied.</li><li>Any claims made with respect to the guarantee and its adjunct warranty should be made directly to the Sonidos or the authorized dealer from which the product was purchased.</li><li>The guaranteed card given to you at the time of purchase must be produced whenever a claim is made.</li><li>The warranty period for a product is 12 months from the date of purchase and 5 years from the date of purchase for all acoustic pianos.</li>";
		
	}else if ('Rentals' == data){
		document.getElementById("description").innerHTML = "<p1>Rates & Rentals</p1>";
	}
}